<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Asl;

/**
 * AslRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AslRepository extends DocumentRepository
{
    public function createAsl($datas, $identifier)
    {
        $asl = new Asl();
        $asl->setIdentifier($identifier);
        $asl->setName($datas->get('name'));
        $asl->setAddress($datas->get('address'));
        $asl->setPostalCode($datas->get('postalCode'));
        $asl->setCity($datas->get('city'));
        $asl->setCountry($datas->get('country'));
        $asl->setCreatedAt(new \DateTime());

        $this->dm->persist($asl);
        $this->dm->flush();
        
        return $asl;
    }
    
    public function findAndUpdateAsl($datas, $asl)
    {
        $aslUpdate = $this->dm->createQueryBuilder('FdsAslMongoBundle:Asl')
            ->findAndUpdate()
            ->field('identifier')->equals((int) $asl->getIdentifier());
            // Update found asl
        foreach ($datas->all() as $key => $value) {
            $aslUpdate->field($key)->set($value);
        }
        
        $aslUpdate->getQuery()
            ->execute();
    }
    
}
