<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Asl;

/**
 * AslRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AslRepository extends DocumentRepository
{
    public function createAsl($request, $identifier)
    {
        $asl = new Asl();
        $asl->setIdentifier($identifier);
        $asl->setName($request->request->get('name'));
        $asl->setAddress($request->request->get('address'));
        $asl->setPostalCode($request->request->get('postalCode'));
        $asl->setCity($request->request->get('city'));
        $asl->setCountry($request->request->get('country'));

        $this->dm->persist($asl);
        $this->dm->flush();
    }
    
    public function findAndUpdateAsl($datas, $asl)
    {
        $aslUpdate = $this->dm->createQueryBuilder('FdsAslMongoBundle:Asl')
            ->findAndUpdate()
            ->field('identifier')->equals((int) $asl->getIdentifier());
            // Update found asl
        foreach ($datas->all() as $key => $value) {
            $aslUpdate->field($key)->set($value);
        }
        
        $aslUpdate->getQuery()
            ->execute();
    }
    
}
