<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Membershipfee;

/**
 * MembershipfeeRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MembershipfeeRepository extends DocumentRepository
{
    public function createMembershipfee($request, $identifier, $asl) 
    {
        //Format string to DateTime
        $date = new \DateTime($request->request->get('year'));
            
        $membershipfee = new Membershipfee();
        $membershipfee->setIdentifier($identifier);
        $membershipfee->setYear($date);
        $membershipfee->setFee($request->request->get('fee'));
        $membershipfee->setAsl($asl);
            
        $this->dm->persist($membershipfee);
            
        $asl->addMembershipfees($membershipfee);
        $this->dm->persist($asl);
        $this->dm->flush();
        
        return $membershipfee;
    }
    
    
    public function deleteMembershipfee($membershipfee_id, $asl) 
    {
        $membershipfees = $asl->getMembershipfees();
        foreach ($membershipfees as $membershipfee) {
            if (
                (int) $membershipfee->getIdentifier() == 
                (int) $membershipfee_id
            ) {
                //remove membershipfee reference in Asl Document
                $asl->getMembershipfees()->removeElement($membershipfee);
                //Remove Document membershipfee
                $this->dm->remove($membershipfee);
                $this->dm->flush();
            }
        }
    }
    
    public function findAndUpdateMembership($request, $membershipfee)
    {
        $membershipfeeUpdate = $this->dm
            ->createQueryBuilder('FdsAslMongoBundle:Membershipfee')
            ->findAndUpdate()
            ->field('identifier')->equals((int) $membershipfee->getIdentifier());
        // Update found membershipfee
        foreach ($request->request->all() as $key => $value) {
            $membershipfeeUpdate->field($key)->set($value);
        }
        $membershipfeeUpdate->getQuery()->execute();
    }
}
