<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Payment;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends DocumentRepository
{
    
    public function createPayment(
        $request, 
        $getIdPlusOneAdded, 
        $asl, 
        $property,
        $owner
    ) {                    
        //Recherche 
    }
}
