<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Property;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends DocumentRepository
{
    public function createProperty($request, $identifier, $asl) 
    {
        $property = new Property();
        $property->setIdentifier($identifier);
        $property->setNumber($request->request->get('number'));
        $property->setPropertyType($request->request->get('propertyType'));
        $property->setAsl($asl);
            
        $this->dm->persist($property);
        
        $asl->addProperties($property);
        $this->dm->persist($asl);
        $this->dm->flush();
    }
    
    public function deleteProperty($property_id, $asl) 
    {
        $properties = $asl->getProperties();
        foreach ($properties as $property) {
            if (
                (int) $property->getIdentifier() == 
                (int) $property_id
            ) {
            //remove property reference in Asl Document
                $asl->getProperties()->removeElement($property);
            //Remove Document property
                $this->dm->remove($property);
            }
        } 
    }
    
    public function findAndUpdateProperty($datas, $property)
    {
        $propertyUpdate = $this->dm
            ->createQueryBuilder('FdsAslMongoBundle:Property')
            ->findAndUpdate()
            ->field('identifier')->equals((int) $property->getIdentifier());
        // Update found membershipfee
        foreach ($datas->all() as $key => $value) {
            $propertyUpdate->field($key)->set($value);
        }
        
        $propertyUpdate->getQuery()
            ->execute();
    }
}
