<?php

namespace Fds\AslMongoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Fds\AslMongoBundle\Document\Resident;

/**
 * ResidentRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends DocumentRepository
{
    public function createResident($request, $identifier, $asl, $property) {
                        
        $resident = new Resident();
        $resident->setIdentifier($identifier);
        $resident->setFirstName($request->request->get('firstName'));
        $resident->setLastName($request->request->get('lastName'));
        $resident->setEmail($request->request->get('email'));
        $resident->setAsl($asl);
        $resident->setProperty($property);                
            
        $this->dm->persist($resident);
                
        $property->addResidents($resident);
        $this->dm->persist($property);
            
        $this->dm->flush();
        
        return $resident;
    }
    
    public function deleteResident($resident, $property) {
        //remove resident reference in Property Document
        $property->getResidents()->removeElement($resident);
        $this->dm->persist($property);
        //Remove Document resident
        $this->dm->remove($resident);
                    
        $this->dm->flush();      
    }
    
    public function keepTrackResident($resident, $property, $endAt) {                  
        //remove resident reference in Property Document
        $property->getResidents()->removeElement($resident);
        $this->dm->persist($property);
        //Add endAt to resident Element and delete relation to Property Element
        //Format string to DateTime
        $date = new \DateTime($endAt);
        $resident->setEndAt($date);
        $resident->setProperty('');
        
        $this->dm->flush();           
    }
    
    public function findAndUpdateResident($request, $resident)
    {
        $residentUpdate = $this->dm
            ->createQueryBuilder('FdsAslMongoBundle:Resident')
            ->findAndUpdate()
            ->field('identifier')->equals((int) $resident->getIdentifier());
        // Update found resident
        foreach ($request->request->all() as $key => $value) {
            $residentUpdate->field($key)->set($value);
        }
        
        $residentUpdate->getQuery()->execute();
    }
        
}
