get_asls:
    path:     /asls
    defaults: { _controller: FdsAslMongoBundle:Asl:getAsls }
    methods:  [GET]
get_asl:
    path:     /asls/{asl_id}
    defaults: { _controller: FdsAslMongoBundle:Asl:getAsl }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
post_asl:
    path:     /asls
    defaults: { _controller: FdsAslMongoBundle:Asl:postAsls }
    methods:  [POST]
delete_asl:
    path:     /asls/{asl_id}
    defaults: { _controller: FdsAslMongoBundle:Asl:deleteAsl }
    methods:  [DELETE]
    requirements:
        asl_id: '\d+'
put_asl:
    path:     /asls/{asl_id}
    defaults: { _controller: FdsAslMongoBundle:Asl:putAsl }
    methods:  [PUT]
    requirements:
        asl_id: '\d+'
patch_asl:
    path:     /asls/{asl_id}
    defaults: { _controller: FdsAslMongoBundle:Asl:patchAsl }
    methods:  [PATCH]
    requirements:
        asl_id: '\d+'

