get_owners:
    path:     /asls/{asl_id}/owners
    defaults: { _controller: FdsAslMongoBundle:Owner:getOwners }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
get_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners
    defaults: { _controller: FdsAslMongoBundle:Owner:getOwner }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
post_owner:
    path:     /owners
    defaults: { _controller: FdsAslMongoBundle:Owner:postOwners }
    methods:  [POST]
    requirements:
        asl_id: '\d+'
delete_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:deleteOwner }
    methods:  [DELETE]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
put_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:putOwner }
    methods:  [PUT]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
patch_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:patchOwner }
    methods:  [PATCH]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'

