get_owners_asl:
    path:     /asls/{asl_id}/owners
    defaults: { _controller: FdsAslMongoBundle:Owner:getOwnersAsl }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
get_owners_property:
    path:     /asls/{asl_id}/properties/{property_id}/owners
    defaults: { _controller: FdsAslMongoBundle:Owner:getOwnersProperty }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
get_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:getOwner }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
post_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners
    defaults: { _controller: FdsAslMongoBundle:Owner:postOwner }
    methods:  [POST]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
delete_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:deleteOwner }
    methods:  [DELETE]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
patch_owner:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:patchOwner }
    methods:  [PATCH]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'