#All payments done for Asl
get_payments:
    path:     /asls/{asl_id}/payments
    defaults: { _controller: FdsAslMongoBundle:Payment:getPayments }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
#All payments done for a Membershipfee
get_property_payments:
    path:     /asls/{asl_id}/membershipfees/{membershipfee_id}/payments
    defaults: { _controller: FdsAslMongoBundle:Payment:getMembershipfeePayments }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        membershipfee_id: '\d+'
#All payements done for a Property 
get_property_payment:
    path:     /asls/{asl_id}/properties/{property_id}/payments
    defaults: { _controller: FdsAslMongoBundle:Payment:getPropertyPayment }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
#One payment for a Property
get_property_payment:
    path:     /asls/{asl_id}/properties/{property_id}/payments/{payment_id}
    defaults: { _controller: FdsAslMongoBundle:Payment:getPropertyPayment }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        payment_id: '\d+' 
#All payments done for an Owner
get_owner_payments:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}/payments
    defaults: { _controller: FdsAslMongoBundle:Payment:getOwnerPayments }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
#One payment for an Owner
get_owner_payment:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}/payments/{payment_id}
    defaults: { _controller: FdsAslMongoBundle:Payment:getOwnerPayment }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
        payment_id: '\d+'
#Create Payment by Owner for Membershipfees
post_owner_payment:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}/payments
    defaults: { _controller: FdsAslMongoBundle:Payment:postPayments }
    methods:  [POST]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+' 
delete_owner_payment:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}/payments/{payment_id}
    defaults: { _controller: FdsAslMongoBundle:Payment:deleteOwnerPayment }
    methods:  [DELETE]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
        payment_id: '\d+'

patch_owner_payment:
    path:     /asls/{asl_id}/properties/{property_id}/owners/{owner_id}/payments/{payment_id}
    defaults: { _controller: FdsAslMongoBundle:Owner:patchPayment }
    methods:  [PATCH]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
        owner_id: '\d+'
        payment_id: '\d+'


