get_properties:
    path:     /asls/{asl_id}/properties
    defaults: { _controller: FdsAslMongoBundle:Property:getProperties }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
get_property:
    path:     /asls/{asl_id}/properties/{property_id}
    defaults: { _controller: FdsAslMongoBundle:Property:getProperty }
    methods:  [GET]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
post_property:
    path:     /asls/{asl_id}/properties
    defaults: { _controller: FdsAslMongoBundle:Property:postProperties }
    methods:  [POST]
    requirements:
        asl_id: '\d+'
delete_property:
    path:     /asls/{asl_id}/properties/{property_id}
    defaults: { _controller: FdsAslMongoBundle:Property:deleteProperty }
    methods:  [DELETE]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
put_property:
    path:     /asls/{asl_id}/properties/{property_id}
    defaults: { _controller: FdsAslMongoBundle:Property:putProperty }
    methods:  [PUT]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'
patch_property:
    path:     /asls/{asl_id}/properties/{property_id}
    defaults: { _controller: FdsAslMongoBundle:Property:patchProperty }
    methods:  [PATCH]
    requirements:
        asl_id: '\d+'
        property_id: '\d+'

