parameters:
    constant_asl: Asl
    constant_membershipfee: Membershipfee
    constant_owner: Owner
    constant_payment: Payment
    constant_property: Property
    constant_resident: Resident
    constant_mem_or_pro: Property Or Membershipfee related
    
services:
#    fds_asl.example:
#        class: Fds\AslBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    # Mongo Service
    fds_mongoservice.mongoservice:
        class: Fds\AslMongoBundle\Service\MongoService
        arguments: ["@doctrine.odm.mongodb.document_manager"]
    # FOSView Service
    fds_fosviewservice.fosviewservice:
        class: Fds\AslMongoBundle\Service\FOSViewService
    #Cache Service
    fds_cacheservice.cacheservice:
        class: Fds\AslMongoBundle\Service\CacheService
