# src/Fds/AslBundle/Resources/config/serialization.yml
FdsAslBundle\Entity\Asl:
    attributes:
        id:
            groups: ['asl', 'property']
        name:
            groups: ['asl', 'property']
        address:
            groups: ['asl', 'property']
        postalCode:
            groups: ['asl', 'property']
        city:
            groups: ['asl', 'property']
        country:
            groups: ['asl', 'property']
        properties:
            groups: ['asl']


FdsAslBundle\Entity\Property:
    attributes:
        id:
            groups: ['asl', 'property']
        number:
            groups: ['asl', 'property']
        type:
            groups: ['asl', 'property']
        asl:
            groups: ['property']
