# src/Fds/AslBundle/Resources/config/serialization.yml
Fds\AslBundle\Entity\Asl:
    attributes:
        id:
            groups: ['asls','asl', 'property', 'membershipfee']
        name:
            groups: ['asls','asl', 'property', 'membershipfee']
        address:
            groups: ['asls','asl', 'property', 'membershipfee']
        postalCode:
            groups: ['asls','asl', 'property', 'membershipfee']
        city:
            groups: ['asls','asl', 'property', 'membershipfee']
        country:
            groups: ['asls','asl', 'property', 'membershipfee']

Fds\AslBundle\Entity\Property:
    attributes:
        id:
            groups: ['asl', 'property', 'owner', 'resident']
        number:
            groups: ['asl', 'property', 'owner', 'resident']
        propertytype:
            groups: ['asl', 'property', 'owner', 'resident']
        asl:
            groups: ['property']
        owners:
            groups: ['asl', 'property', 'owner']
        residents:
            groups: ['asl', 'property', 'resident']
            
Fds\AslBundle\Entity\MembershipFee:
    attributes:
        id:
            groups: ['asl', 'membershipfee']
        year:
            groups: ['asl', 'membershipfee']
        fee:
            groups: ['asl', 'membershipfee']
        asl:
            groups: ['membershipfee']
            
Fds\AslBundle\Entity\Owner:
    attributes:
        id:
            groups: ['owner', 'asl', 'property']
        firstName:
            groups: ['owner', 'asl', 'property']
        lastName:
            groups: ['owner', 'asl', 'property']
        email:
            groups: ['owner', 'asl', 'property']
        phone:
            groups: ['owner', 'asl', 'property']
        propertyasaddress:
            groups: ['owner', 'asl', 'property']
        address:
            groups: ['owner', 'asl', 'property']
        postalcode:
            groups: ['owner', 'asl', 'property']
        city:
            groups: ['owner', 'asl', 'property']
        country:
            groups: ['owner', 'asl', 'property']
            
Fds\AslBundle\Entity\Resident:
    attributes:
        id:
            groups: ['resident', 'asl', 'property']
        firstName:
            groups: ['resident', 'asl', 'property']
        lastName:
            groups: ['resident', 'asl', 'property']
        email:
            groups: ['resident', 'asl', 'property']
        phone:
            groups: ['resident', 'asl', 'property'] 