# src/FdsAslBundle/Resources/config/validation.yml
FdsAslBundle\Entity\Asl:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string
        postalCode:
            - NotBlank: ~
            - Type: string
        city:
            - NotBlank: ~
            - Type: string
        country:
            - NotBlank: ~
            - Type: string

FdsAslBundle\Entity\Property:
    properties:
        number:
            - NotNull: ~
        type:
            - NotNull: ~
            - Choice:
                choices: [House, Appartment]
                
Fds\AslBundle\Entity\MembershipFee:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: year
    properties:
        year:
            - NotBlank: ~
            - Type: date
        fee:
            - NotBlank: ~
            - Type: string