fds_auth:
    resource: "@FdsAuthBundle/Resources/config/routing.yml"
    prefix:   /

fds_asl_mongo:
    resource: "@FdsAslMongoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation