<?php

namespace Fds\AslBundle\Repository;

/**
 * AslRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AslRepository extends \Doctrine\ORM\EntityRepository
{
}
