<?php

namespace Fds\AslBundle\Repository;

/**
 * MembershipFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
