<?php

namespace Fds\AslBundle\Repository;

/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends \Doctrine\ORM\EntityRepository
{
}
