parameters:
    constant_user: User
    
services:
    auth_token_user_provider:
        class: Fds\AuthBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ODM\MongoDB\DocumentManager
        factory: ["@doctrine.odm.mongodb.document_manager", "getRepository"]
        arguments: ["FdsAuthBundle:AuthToken"]

    user_repository:
        class:   Doctrine\ODM\MongoDB\DocumentManager
        factory: ["@doctrine.odm.mongodb.document_manager", "getRepository"]
        arguments: ["FdsAuthBundle:User", "FdsAslMongoBundle:Owner"]

    auth_token_authenticator:
        class:     Fds\AuthBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false