Fds\AslBundle\Entity\Membershipfee:
    type: entity
    table: membershipfee
    indexes:
        FK_EFBBF54824E8B3DA:
            columns:
                - asl_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: date
            nullable: false
        fee:
            type: decimal
            nullable: true
            precision: 6
            scale: 2
    manyToOne:
        asl:
            targetEntity: Asl
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                asl_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
