Fds\AslBundle\Entity\Owner:
    type: entity
    table: owner
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lastName
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        propertyasaddress:
            type: boolean
            nullable: true
            column: propertyasaddress
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        postalcode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: postalCode
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        property:
            targetEntity: Property
            cascade: {  }
            fetch: LAZY
            mappedBy: owner
            inversedBy: null
            joinTable: null
            orderBy: null    
    lifecycleCallbacks: {  }
