Fds\AslBundle\Entity\Property:
    type: entity
    table: property
    indexes:
        FK_8BF21CDE24E8B3DA:
            columns:
                - asl_id
        FK_8BF21CDE9C81C6EB:
            columns:
                - propertytype_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        number:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        propertytype:
            targetEntity: Propertytype
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                propertytype_id:
                    referencedColumnName: id
            orphanRemoval: false
        asl:
            targetEntity: Asl
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                asl_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        residents:
            targetEntity: Resident
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: property
            joinTable:
                name: property_resident
                joinColumns:
                    -
                        name: property_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: resident_id
                        referencedColumnName: id
            orderBy: null
        owners:
            targetEntity: Owner
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: property
            joinTable:
                name: property_owner
                joinColumns:
                    -
                        name: property_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: owner_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
