Fds\AslBundle\Entity\Resident:
    type: entity
    table: resident
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: lastName
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        property:
            targetEntity: Property
            cascade: {  }
            fetch: LAZY
            mappedBy: resident
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
