<?php

namespace Fds\AuthBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

use Fds\AslMongoBundle\Document\Owner;
use Fds\AuthBundle\Document\User;
use Fds\AuthBundle\Document\AuthToken;

/**
 * AuthTokenRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends DocumentRepository
{
    public function managerLogin($email)
    {
        $manager = $this->getDocumentManager()
            ->getRepository('FdsAuthBundle:User')
            ->findOneByEmail($email);

        if ($manager instanceof User) {
            return $manager;
        } else {
            return false;
        }
    }
    
    public function viewerLogin($email)
    {
        $viewer = $this->getDocumentManager()
            ->getRepository('FdsAslMongoBundle:Owner')
            ->findOneByEmail($email);

        if ($viewer instanceof Owner) {
            return $viewer;
        } else {
            return false;
        }
    }
    
    public function tokenCreator($user)
    { 
        $authToken = new AuthToken();
        $authToken->setValue(base64_encode(random_bytes(50)));
        $authToken->setUser($user);
        
        $this->getDocumentManager()->persist($authToken);
        $this->getDocumentManager()->flush();

        return $authToken;
    }
}
